version: '3'
services:

  #PHP Service
  app:
    build: .docker
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
    networks:
      - app-network

  # Web server
  web:
    image: nginx:mainline
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: always
    tty: true
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql/
      - .docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  worker:
      build: .docker/php-worker
      depends_on:
          - db
      volumes:
          - ./:/var/workspace
          - ./.docker/php-worker/workers:/etc/supervisor/conf.d
          - ./.docker/php-worker/logs:/var/log/workers
      networks:
          - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
